flyway.locations=filesystem:01_ddl,filesystem:02_dml,filesystem:03_dcl,filesystem:04_tcl
flyway.validateMigrationNaming=true
flyway.cleanDisabled=true
flyway.schemas=medical_consultation
flyway.defaultSchema=medical_consultation
flyway.table=flyway_history_medical_consultation
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.postgresql.transactional.lock=false
